name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 当推送到 main 分支时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js and dependencies
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'  # v4 才支持 yarn 缓存

    - name: Install dependencies
      run: yarn install --frozen-lockfile # 确保锁定依赖版本，避免意外更新

    - name: Build project
      run: yarn build # 构建项目，生成 dist 文件夹

    - name: Check dist folder contents
      run: ls -la ./dist # 确保 dist 文件夹正确生成

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # 部署 dist 文件夹
